In [1]:
import xarray as xr
import numpy as np

## 查看一般的surfacedata中的UrbanAlbedo的数据结构

In [2]:
fname = "surfdata_0.9x1.25_hist_78pfts_CMIP6_simyr1850_c190214.nc"
ds = xr.open_dataset(fname)
ds

<xarray.Dataset>
Dimensions:                  (lsmlat: 192, lsmlon: 288, nlevsoi: 10,
                              natpft: 15, cft: 64, time: 12, lsmpft: 79,
                              numurbl: 3, numrad: 2, nlevurb: 5, nglcecp1: 11,
                              nglcec: 10)
Coordinates:
  * natpft                   (natpft) int32 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14
  * cft                      (cft) int32 15 16 17 18 19 20 ... 73 74 75 76 77 78
  * time                     (time) int32 1 2 3 4 5 6 7 8 9 10 11 12
Dimensions without coordinates: lsmlat, lsmlon, nlevsoi, lsmpft, numurbl,
                                numrad, nlevurb, nglcecp1, nglcec
Data variables: (12/77)
    mxsoil_color             int32 ...
    SOIL_COLOR               (lsmlat, lsmlon) int32 ...
    PCT_SAND                 (nlevsoi, lsmlat, lsmlon) float64 ...
    PCT_CLAY                 (nlevsoi, lsmlat, lsmlon) float64 ...
    ORGANIC                  (nlevsoi, lsmlat, lsmlon) float64 ...
    FMAX                     (lsmlat, lsmlon) float64 ...
    ...                       ...
    CONST_HARVEST_SH2        (lsmlat, lsmlon) float64 ...
    CONST_HARVEST_SH3        (lsmlat, lsmlon) float64 ...
    CONST_GRAZING            (lsmlat, lsmlon) float64 ...
    CONST_FERTNITRO_CFT      (cft, lsmlat, lsmlon) float64 ...
    UNREPRESENTED_PFT_LULCC  (natpft, lsmlat, lsmlon) float64 ...
    UNREPRESENTED_CFT_LULCC  (cft, lsmlat, lsmlon) float64 ...
Attributes: (12/47)
    Conventions:                          NCAR-CSM
    History_Log:                          created on: 02-14-19 10:20:45
    Logname:                              erik
    Host:                                 cheyenne3
    Source:                               Community Land Model: CLM5
    Version:                              release-clm5.0.18/gpfs/fs1/scratch/...
    ...                                   ...
    Soil_texture_raw_data_file_name:      mksrf_soitex.10level.c010119.nc
    Soil_color_raw_data_file_name:        mksrf_soilcolor_CMIP6_simyr2005.c17...
    Fmax_raw_data_file_name:              mksrf_fmax_3x3min_USGS_c120911.nc
    Organic_matter_raw_data_file_name:    mksrf_organic_10level_5x5min_ISRIC-...
    Lai_raw_data_file_name:               mksrf_lai_78pfts_simyr2005.c170413.nc
    Vegetation_type_raw_data_filename:    mksrf_landuse_histclm50_LUH2_1850.c...

In [3]:
coords = ds.coords
coords

Coordinates:
  * natpft   (natpft) int32 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14
  * cft      (cft) int32 15 16 17 18 19 20 21 22 23 ... 71 72 73 74 75 76 77 78
  * time     (time) int32 1 2 3 4 5 6 7 8 9 10 11 12

In [4]:
dims = ds.dims
dims

Frozen({'lsmlat': 192, 'lsmlon': 288, 'nlevsoi': 10, 'natpft': 15, 'cft': 64, 'time': 12, 'lsmpft': 79, 'numurbl': 3, 'numrad': 2, 'nlevurb': 5, 'nglcecp1': 11, 'nglcec': 10})

In [5]:
variables = ds.variables
variables

Frozen({'mxsoil_color': <xarray.Variable ()>
[1 values with dtype=int32]
Attributes:
    long_name:  maximum numbers of soil colors
    units:      unitless, 'SOIL_COLOR': <xarray.Variable (lsmlat: 192, lsmlon: 288)>
[55296 values with dtype=int32]
Attributes:
    long_name:  soil color
    units:      unitless, 'PCT_SAND': <xarray.Variable (nlevsoi: 10, lsmlat: 192, lsmlon: 288)>
[552960 values with dtype=float64]
Attributes:
    long_name:  percent sand
    units:      unitless, 'PCT_CLAY': <xarray.Variable (nlevsoi: 10, lsmlat: 192, lsmlon: 288)>
[552960 values with dtype=float64]
Attributes:
    long_name:  percent clay
    units:      unitless, 'ORGANIC': <xarray.Variable (nlevsoi: 10, lsmlat: 192, lsmlon: 288)>
[552960 values with dtype=float64]
Attributes:
    long_name:  organic matter density at soil levels
    units:      kg/m3 (assumed carbon content 0.58 gC per gOM), 'FMAX': <xarray.Variable (lsmlat: 192, lsmlon: 288)>
[55296 values with dtype=float64]
Attributes:
    long_

In [6]:
time = ds.variables['time']
time

<xarray.IndexVariable 'time' (time: 12)>
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)
Attributes:
    long_name:  Calendar month
    units:      month

In [7]:
ALB_IMPROAD_DIR =ds.variables['ALB_IMPROAD_DIR']
ALB_IMPROAD_DIR

<xarray.Variable (numrad: 2, numurbl: 3, lsmlat: 192, lsmlon: 288)>
[331776 values with dtype=float64]
Attributes:
    long_name:  direct albedo of impervious road
    units:      unitless

In [8]:
T_BUILDING_MIN = ds.variables['T_BUILDING_MIN']
T_BUILDING_MIN

<xarray.Variable (numurbl: 3, lsmlat: 192, lsmlon: 288)>
[165888 values with dtype=float64]
Attributes:
    long_name:  minimum interior building temperature
    units:      K

In [9]:
cft = ds.variables['cft']
cft

<xarray.IndexVariable 'cft' (cft: 64)>
array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78], dtype=int32)
Attributes:
    long_name:  indices of CFTs
    units:      index

In [10]:
natpft = ds.variables['natpft']
natpft

<xarray.IndexVariable 'natpft' (natpft: 15)>
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14], dtype=int32)
Attributes:
    long_name:  indices of natural PFTs
    units:      index

In [11]:
cv_wall = ds.variables['ALB_ROOF_DIR'][:,:,1,1]
print(np.array(cv_wall))

[[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
attrs = ds.attrs
attrs

{'Conventions': 'NCAR-CSM',
 'History_Log': 'created on: 02-14-19 10:20:45',
 'Logname': 'erik',
 'Host': 'cheyenne3',
 'Source': 'Community Land Model: CLM5',
 'Version': 'release-clm5.0.18/gpfs/fs1/scratch/erik/release-clm5.0.18/tools/mksurfdata_map',
 'Compiler_Optimized': 'TRUE',
 'no_inlandwet': 'TRUE',
 'nglcec': 10,
 'Input_grid_dataset': 'map_0.25x0.25_MODIS_to_0.9x1.25_nomask_aave_da_c170321.nc',
 'Input_gridtype': 'global',
 'VOC_EF_raw_data_file_name': 'mksrf_vocef_0.5x0.5_simyr2000.c110531.nc',
 'Inland_lake_raw_data_file_name': 'mksrf_LakePnDepth_3x3min_simyr2004_csplk_c151015.nc',
 'Inland_wetland_raw_data_file_name': 'mksrf_lanwat.050425.nc',
 'Glacier_raw_data_file_name': 'mksrf_glacier_3x3min_simyr2000.c120926.nc',
 'Glacier_region_raw_data_file_name': 'mksrf_GlacierRegion_10x10min_nomask_c170616.nc',
 'Urban_Topography_raw_data_file_name': 'mksrf_topo.10min.c080912.nc',
 'Urban_raw_data_file_name': 'mksrf_urban_0.05x0.05_simyr2000.c120621.nc',
 'agfirepkmon_raw_data_f

## 查看tbuildmax的数据结构

In [13]:
fname2 = "CLM50_tbuildmax_Oleson_2016_0.9x1.25_simyr1849-2106_c160923.nc"
ds2 = xr.open_dataset(fname2)
ds2

<xarray.Dataset>
Dimensions:        (lat: 192, lon: 288, time: 258, nv: 2)
Coordinates:
  * lat            (lat) float64 -90.0 -89.06 -88.12 -87.17 ... 88.12 89.06 90.0
  * lon            (lon) float64 0.0 1.25 2.5 3.75 ... 355.0 356.2 357.5 358.7
  * time           (time) object 1849-01-01 00:00:00 ... 2106-01-01 00:00:00
Dimensions without coordinates: nv
Data variables:
    LATIXY         (lat, lon) float64 ...
    LONGXY         (lat, lon) float64 ...
    LANDMASK       (lat, lon) int32 ...
    area           (lat, lon) float64 ...
    year           (time) int32 ...
    time_bnds      (time, nv) object ...
    tbuildmax_TBD  (time, lat, lon) float64 ...
    tbuildmax_HD   (time, lat, lon) float64 ...
    tbuildmax_MD   (time, lat, lon) float64 ...
Attributes:
    date:     Fri Jun 10 13:15:08 MDT 2016
    case_id:  Base data is from surfdata_0.9x1.25_16pfts_simyr2000_c160127.nc
    source:   /glade/p/cgd/tss/people/oleson/urban_sfcdata/Feddema_urban_data...
    title:    Streams File for Maximum Building Interior Temperature for TBD,...
    history:  Mon Aug  1 15:51:49 2016: ncatted -a long_name,tbuildmax_TBD,o,...

In [14]:
time = ds2.variables['time']
time

<xarray.IndexVariable 'time' (time: 258)>
array([cftime.DatetimeNoLeap(1849, 1, 1, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(1850, 1, 1, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(1851, 1, 1, 0, 0, 0, 0, has_year_zero=True), ...,
       cftime.DatetimeNoLeap(2104, 1, 1, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2105, 1, 1, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2106, 1, 1, 0, 0, 0, 0, has_year_zero=True)],
      dtype=object)
Attributes:
    long_name:  time

In [15]:
lon = ds2.variables['lon']
lon

<xarray.IndexVariable 'lon' (lon: 288)>
array([  0.  ,   1.25,   2.5 , ..., 356.25, 357.5 , 358.75])
Attributes:
    units:      degrees_east
    long_name:  longitude

In [16]:
lat = ds2.variables['lat']
lat

<xarray.IndexVariable 'lat' (lat: 192)>
array([-90.      , -89.057592, -88.115183, -87.172775, -86.230366, -85.287958,
       -84.34555 , -83.403141, -82.460733, -81.518325, -80.575916, -79.633508,
       -78.691099, -77.748691, -76.806283, -75.863874, -74.921466, -73.979058,
       -73.036649, -72.094241, -71.151832, -70.209424, -69.267016, -68.324607,
       -67.382199, -66.439791, -65.497382, -64.554974, -63.612565, -62.670157,
       -61.727749, -60.78534 , -59.842932, -58.900524, -57.958115, -57.015707,
       -56.073298, -55.13089 , -54.188482, -53.246073, -52.303665, -51.361257,
       -50.418848, -49.47644 , -48.534031, -47.591623, -46.649215, -45.706806,
       -44.764398, -43.82199 , -42.879581, -41.937173, -40.994764, -40.052356,
       -39.109948, -38.167539, -37.225131, -36.282723, -35.340314, -34.397906,
       -33.455497, -32.513089, -31.570681, -30.628272, -29.685864, -28.743455,
       -27.801047, -26.858639, -25.91623 , -24.973822, -24.031414, -23.089005,
       -22.146597, -21.204188, -20.26178 , -19.319372, -18.376963, -17.434555,
       -16.492147, -15.549738, -14.60733 , -13.664921, -12.722513, -11.780105,
       -10.837696,  -9.895288,  -8.95288 ,  -8.010471,  -7.068063,  -6.125654,
        -5.183246,  -4.240838,  -3.298429,  -2.356021,  -1.413613,  -0.471204,
         0.471204,   1.413613,   2.356021,   3.298429,   4.240838,   5.183246,
         6.125654,   7.068063,   8.010471,   8.95288 ,   9.895288,  10.837696,
        11.780105,  12.722513,  13.664921,  14.60733 ,  15.549738,  16.492147,
        17.434555,  18.376963,  19.319372,  20.26178 ,  21.204188,  22.146597,
        23.089005,  24.031414,  24.973822,  25.91623 ,  26.858639,  27.801047,
        28.743455,  29.685864,  30.628272,  31.570681,  32.513089,  33.455497,
        34.397906,  35.340314,  36.282723,  37.225131,  38.167539,  39.109948,
        40.052356,  40.994764,  41.937173,  42.879581,  43.82199 ,  44.764398,
        45.706806,  46.649215,  47.591623,  48.534031,  49.47644 ,  50.418848,
        51.361257,  52.303665,  53.246073,  54.188482,  55.13089 ,  56.073298,
        57.015707,  57.958115,  58.900524,  59.842932,  60.78534 ,  61.727749,
        62.670157,  63.612565,  64.554974,  65.497382,  66.439791,  67.382199,
        68.324607,  69.267016,  70.209424,  71.151832,  72.094241,  73.036649,
        73.979058,  74.921466,  75.863874,  76.806283,  77.748691,  78.691099,
        79.633508,  80.575916,  81.518325,  82.460733,  83.403141,  84.34555 ,
        85.287958,  86.230366,  87.172775,  88.115183,  89.057592,  90.      ])
Attributes:
    units:      degree_north
    long_name:  latitude

In [17]:
print(ds2['time'])

<xarray.DataArray 'time' (time: 258)>
array([cftime.DatetimeNoLeap(1849, 1, 1, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(1850, 1, 1, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(1851, 1, 1, 0, 0, 0, 0, has_year_zero=True), ...,
       cftime.DatetimeNoLeap(2104, 1, 1, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2105, 1, 1, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2106, 1, 1, 0, 0, 0, 0, has_year_zero=True)],
      dtype=object)
Coordinates:
  * time     (time) object 1849-01-01 00:00:00 ... 2106-01-01 00:00:00
Attributes:
    long_name:  time


## 切片
- [:]是全切
- [0:2]是切除第0个和第1个

In [18]:
lat = ds2.variables['lat'][0:2]
lat

<xarray.IndexVariable 'lat' (lat: 2)>
array([-90.      , -89.057592])
Attributes:
    units:      degree_north
    long_name:  latitude

In [19]:
lon = ds2.variables['lon'][0:2]
lon

<xarray.IndexVariable 'lon' (lon: 2)>
array([0.  , 1.25])
Attributes:
    units:      degrees_east
    long_name:  longitude

In [20]:
time = ds2.variables['time'][0:2]
time

<xarray.IndexVariable 'time' (time: 2)>
array([cftime.DatetimeNoLeap(1849, 1, 1, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(1850, 1, 1, 0, 0, 0, 0, has_year_zero=True)],
      dtype=object)
Attributes:
    long_name:  time

In [21]:
tbuildmax_TBD = ds2.variables['tbuildmax_TBD'][0:2,0:2,0:2]
tbuildmax_TBD

<xarray.Variable (time: 2, lat: 2, lon: 2)>
[8 values with dtype=float64]
Attributes:
    units:      K
    long_name:  Maximum interior building temperature for Tall Building Distr...

In [23]:
year = ds2.variables['year']
year

<xarray.Variable (time: 258)>
[258 values with dtype=int32]
Attributes:
    long_name:  year
    units:      Year AD